apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    spec:
      containers:
        - name: init
          image: mysql:5.7
          env:
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
          command: ["sh", "-c"]
          args:
            - |
              mysql -hmysql -uroot -e "CREATE TABLE IF NOT EXISTS counterdb.counter (id INT PRIMARY KEY AUTO_INCREMENT, value INT);"
      restartPolicy: OnFailure
